import { createFileRoute } from "@tanstack/react-router";
import { ServiceDetail, OfferingDetail } from "@/components/site/ServiceDetail";

const detailedOfferings: OfferingDetail[] = [
  {
    title: "1. Cyber Dom – AI Security & Guardrails Mesh",
    subtitle: "Continuous runtime protection and policy enforcement for enterprise AI",
    description: "Architecting and deploying Cyber Dom, a highly resilient security and monitoring mesh that wraps around model inputs, API integrations, and agent workflows. Features include active threat analysis, exfiltration blockades, and strict Zero Trust network boundaries.",
    keySituations: [
      "AI systems connecting to high-privilege corporate databases without automated activity guardrails.",
      "Vulnerability to prompt injection, jailbreaking, or toxic payloads targeting enterprise LLMs.",
      "Lack of compliance records for model and agent database/tool executions."
    ],
    keyStatistics: [
      "Jailbreak and prompt injection detection: 99.9% block rate",
      "Network routing overhead: <5ms response latency",
      "Regulatory compliance coverage: SOC2, FedRAMP, and EU AI Act readiness mapped automatically",
      "Incident alert response time: Instantaneous runtime isolation of compromised sessions"
    ],
    offeringValue: "Provides an impenetrable security perimeter around model contexts, tool bindings, and data stores.",
    expectedOutcomes: [
      "Fully audited, secure execution mesh for all internal and external-facing AI endpoints.",
      "Real-time monitoring panel displaying injection alerts, policy violations, and compliance state.",
      "Immutable cryptographic audit trails tracking every database read/write executed by AI components."
    ]
  },
  {
    title: "2. Bash Shell Hardening & Secure Sandbox Execution",
    subtitle: "Dynamic command isolation for executing agent-generated scripts safely",
    description: "Custom-built, hyper-secure command execution environments (leveraging gVisor, WebAssembly sandboxes, and MicroVMs) to execute shell command sequences and dynamic Bash scripts generated by AI agents without risking host or cloud architecture compromises.",
    keySituations: [
      "Agents requiring terminal access (e.g. executing bash commands, configuring systems) to perform their jobs.",
      "Risks of agents writing malicious loop scripts, running resource exhaustion processes, or executing `rm -rf /` commands.",
      "Vulnerability to privilege escalation or lateral network movements from compromised runner containers."
    ],
    keyStatistics: [
      "Sandbox breakout incidents: 0% historical escape rate",
      "Execution latency overhead: <10ms boot time for containerized MicroVMs",
      "CPU/Memory limit enforcement: Strict resource capping prevents Denials of Service",
      "Command filtering efficiency: 100% of banned system calls blocked instantly"
    ],
    offeringValue: "Allows systems to tap into the full potential of shell automation and scripting safely, protecting base systems.",
    expectedOutcomes: [
      "Micro-segmented Bash execution sandbox integrated with agent tooling pathways.",
      "Pre-execution syntax auditing and blacklisted command filters.",
      "Ephemeral container architecture that completely destroys filesystems immediately post-execution."
    ]
  }
];

export const Route = createFileRoute("/ai-security")({
  head: () => ({
    meta: [
      { title: "AI Security, Cyber Dom & Governance — Zero Trust for AI | TrustGrid.AI" },
      { name: "description", content: "Secure AI deployments with Cyber Dom, dynamic Bash sandboxing, Zero Trust Architecture, confidential computing, IAM, compliance, and continuous threat monitoring." },
      { property: "og:title", content: "AI Security & Cyber Dom | TrustGrid.AI" },
      { property: "og:description", content: "Cyber Dom security mesh and secure Bash shell execution sandboxes for autonomous enterprise AI." },
      { property: "og:url", content: "/ai-security" },
    ],
    links: [{ rel: "canonical", href: "/ai-security" }],
  }),
  component: () => (
    <ServiceDetail
      eyebrow="AI Security, Cyber Dom & Governance"
      title="Zero-Trust security for enterprise AI"
      description="We engineer AI systems that meet the security and governance bar of regulated industries — financial services, healthcare, defense and government. Our specialized Cyber Dom and hardened sandboxes protect your core infrastructure from dynamic execution vulnerabilities."
      outcomes={[
        { value: "99.9%", label: "Jailbreak block rate" },
        { value: "0%", label: "Sandbox breakout" },
        { value: "<5ms", label: "Guardrail latency" },
        { value: "100%", label: "System call audits" },
      ]}
      capabilities={[
        { title: "Confidential Computing", desc: "TEE-backed training and inference (NVIDIA H100 CC, Intel TDX)." },
        { title: "Cyber Dom Guardrails", desc: "Continuous runtime protection, input validation, and threat shielding." },
        { title: "Bash Sandbox Isolation", desc: "Secure gVisor/WASM runtimes for dynamic agent-generated script runs." },
        { title: "Identity & Access Control", desc: "Fine-grained IAM for models, tools, agents and data sources." },
        { title: "Audit Trails & Compliance", desc: "Immutable logs for model calls, SOC2/FedRAMP/EU AI Act readiness." },
        { title: "Adversarial Red-Teaming", desc: "Continuous automated testing of LLM and agent attack vectors." },
      ]}
      stack={["NVIDIA Confidential Compute", "gVisor", "WebAssembly", "HashiCorp Vault", "Okta", "Wiz", "Lakera", "Robust Intelligence"]}
      detailedOfferings={detailedOfferings}
    />
  ),
});
